name: Check Out of Date

on: [push]
permissions:
  contents: write

jobs:
  check:
    runs-on: windows-latest
    concurrency: ci-${{ github.ref }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Check Last Commit
      id: checklastcommit
      run: .\checkoutdate.ps1
      shell: powershell
      
    - name: Create New CSharp.lua dll
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      run: createnewfiles
      shell: cmd
      
    - name: Commit files
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "./bin/files"
        commit-message: "Github Action Auto Commit Files"