name: Check Out of Date

on: [push]
permissions:
  contents: write

jobs:
  check:
    runs-on: windows-latest
    outputs:
      isOutDate: ${{steps.checklastcommit.outputs.isOutDate}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
      
    - name: Check Last Commit
      id: checklastcommit
      run: .\checkoutdate.ps1
      shell: powershell
      
    - name: Create New CSharp.lua dll
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      run: createnewfiles
      shell: cmd
      
    - name: Commit
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply CSharp.lua changes
        branch: main
        commit_options: '--no-verify --signoff'
        file_pattern: files/*.*
        repository: .
        