name: Check Out of Date

on: [push]
permissions:
  contents: write

jobs:
  check:
    runs-on: windows-latest
    outputs:
      isOutDate: ${{steps.checklastcommit.outputs.isOutDate}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Check Last Commit
      id: checklastcommit
      run: .\checkoutdate.ps1
      shell: powershell
      
    - name: Create New CSharp.lua dll
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      run: createnewfiles
      shell: cmd
      
    - name: Upload Files
      if: ${{steps.checklastcommit.outputs.isOutDate}} == 'True'
      uses: actions/upload-artifact@v1
      with:
        name: files
        path: "./bin/files"

  commit:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} 
    needs: check
    if: ${{needs.check.outputs.isOutDate}} == 'True'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download Files
      uses: actions/download-artifact@v1  
      with: 
        name: files
      
    - name: Commit files
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "./"
        branch: "main"
        commit-message: "Github Action Auto Commit Files"